name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: jessedearing
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Push to Docker Hub and GitHub Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          jessedearing/debug:latest
          gchr.io/jessedearing/debug:latest
