name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: jessedearing
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jessedearing/debug
        tag_with_ref: true
    - name: Push to GitHub Registry
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: jessedearing/debug/debug
        tag_with_ref: true
